version: "3"

services:
  
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./postgres/my.conf:/etc/postgresql/postgresql.conf"
      - "./postgres/data:/var/lib/postgresql/data:rw"

  pgadmin:
    image: thajeztah/pgadmin4
    ports:
      - "5050:5050"
    volumes:
      - "./pgadmin4/:/pgadmin:rw"

  redis:
    image: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"  
      - "15672:15672"

  # mysql:
  #   image: mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - "./mysql/my.conf:/etc/mysql/conf.d/config-file.cnf"
  #     - "./mysql/data:/var/lib/mysql:rw"
