version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres
    # auto start container
    # restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      # host port:docker port
      - 5432:5432
    volumes:
      # mount configurations
      - ./postgres/my.conf:/etc/postgresql/postgresql.conf
      # mount data
      - ./postgres/data:/var/lib/postgresql/data:rw
      # mount data for windows use this
      # http://www.lukaszewczak.com/2016/09/run-postgresql-using-docker-with.html
      # docker volume create --name postgres-vol -d local
      # - postgres-vol:/var/lib/postgresql/data:rw

  # mkdir -p pgadmin/{config,storage}
  pgadmin:
    image: thajeztah/pgadmin4
    container_name: pgadmin
    ports:
      - 5050:5050
    volumes:
      # mount configurations
      - ./pgadmin/:/pgadmin:rw
    # if you want to start postgres when starting pgadmin
    # depends_on:
    #   - postgres

  # mkdir -p pgadmin1/data
  pgadmin1:
    image: chorss/docker-pgadmin4
    container_name: pgadmin1
    ports:
      - 5051:5050
    volumes:
      - ./pgadmin1/data:/data chorss/docker-pgadmin4
      - ./pgadmin1/:/pgadmin

  pghero:
    image: ankane/pghero
    container_name: pghero
    ports:
      - 8080:8080
    volumes:
      - ./pghero/pghero.yml:/app/config/pghero.yml

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      # - ./mysql/my.conf:/etc/mysql/conf.d/config-file.cnf
      - ./mysql/data:/var/lib/mysql:rw

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379

  # mongo:
  #   image: mongo
  #   container_name: mongo
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./mongo/data:/data/db

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  fluentd:
    build: ./fluentd/dockerfile
    container_name: fluentd
    ports:
      - 9880:9880
    volumes:
      - ./fluentd/plugins:/fluentd/plugins
      - ./fluentd/etc:/fluentd/etc
    environment:
      - FLUENTD_CONF=fluentd.conf

  php:
    image: php:apache
    container_name: php
    ports:
      - 80:80
    volumes:
      - ~/projects/php:/var/www/html

  # java7:
  #   image: openjdk:7-jdk
  #   container_name: java7

# for windows use this
# volumes:
#   postgres-vol:
#     external: true
