version: "3"

services:

  php:
    container_name: php
    image: php:apache
    ports:
      - 80:80
    volumes:
      - ~/projects/php:/var/www/html

  postgres:
    # restart: unless-stopped
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      # - ./postgres/my.conf:/etc/postgresql/postgresql.conf
      - ./postgres/data:/var/lib/postgresql/data:rw

  # run this first mkdir -p pgadmin/{config,storage}
  pgadmin:
    container_name: pgadmin
    image: thajeztah/pgadmin4
    ports:
      - 5050:5050
    volumes:
      - ./pgadmin/:/pgadmin:rw
    # depends_on:
    #   - postgres

  # run this first mkdir -p pgadmin1/data
  pgadmin1:
    container_name: pgadmin1
    image: chorss/docker-pgadmin4
    ports:
      - 5051:5050
    volumes:
      - ./pgadmin1/data:/data chorss/docker-pgadmin4
      - ./pgadmin1/:/pgadmin

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672

  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      # - ./mysql/my.conf:/etc/mysql/conf.d/config-file.cnf
      - ./mysql/data:/var/lib/mysql:rw
