# docker.for.win.localhost

version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres
    # auto start container
    # restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      # host port:docker port
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - 5050:80
    # volumes:
    # - ./pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  pghero:
    image: ankane/pghero
    container_name: pghero
    ports:
      - 8080:8080
    volumes:
      - ./pghero/pghero.yml:/app/config/pghero.yml

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql:rw

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8080:80
    depends_on:
      - mysql

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    # volumes:
    #   - ./mongo/data:/data/db

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  fluentd:
    build: ./fluentd/dockerfile
    container_name: fluentd
    volumes:
      - ./fluentd:/fluentd
    environment:
      - FLUENTD_CONF=fluentd.conf
    depends_on:
      - redis
      - postgres

  php:
    image: php:apache
    container_name: php
    ports:
      - 80:80
    volumes:
      - ./php:/var/www/html

  ruby_runner:
    build: ./ruby_runner
    container_name: ruby_runner
    volumes:
      - ./ruby_runner:/usr/src/myapp
    command: ruby /usr/src/myapp/read_files.rb
    depends_on:
      - postgres
      - redis

  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
      - 4000:3000
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=postgres
      - MB_DB_PASS=postgres
      - MB_DB_HOST=postgres
    depends_on:
      - postgres

  odoo:
    image: odoo
    container_name: odoo
    ports:
      - 8069:8069
    environment:
      - HOST=postgres
      # - USER=postgres
      # - PASSWORD=postgres
    depends_on:
      - postgres

  mattermost:
    image: mattermost/mattermost-preview
    container_name: mattermost
    ports:
      - 8065:8065

  openhab:
    image: openhab/openhab
    container_name: openhab
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - ./openhab/addons:/openhab/addons
